### ISSUE TITLE
FAIL	AttributeError: 'Namespace' object has no attribute '_testlibs'

### ISSUE THREAD

**Issue by codlin** [robotframework/RemoteApplications#18]
Could you help me check this issue?
version: remoteapplications-2.0.jar swinglibrary-1.7.0.jar/swinglibrary-1.9.1.jar/swinglibrary-1.9.6.jar

KEYWORD RemoteApplications . Take Libraries Into Use SwingLibrary
Documentation:	
Takes the libraries into use at the remote application.
Start / End / Elapsed:	20170313 07:00:02.846 / 20170313 07:00:03.292 / 00:00:00.446
07:00:03.240	INFO	Mar 13, 2017 7:00:03 AM org.robotframework.remoteapplications.org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [org/robotframework/remoteapplications/client/clientContext.xml]	
07:00:03.291	FAIL	AttributeError: 'Namespace' object has no attribute '_testlibs'

Thanks.

**Comment by pekkaklarck** [comment]
Looks like RemoteApplications would be accessing Robot Framework's private API (`Namespace._testlibs`) that has been removed at some point. This project is not maintained anymore, so the problem won't be fixed. You seem to be using SwingLibrary with RemoteApplications, so you ought to be able to switch to using RemoteSwingLibrary instead. Obviously you can also use old enough Robot Framework version that still has the APIs needed by RemoteApplications.
